# Generated by Django 5.1.2 on 2024-10-24 19:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('razao_social', models.CharField(max_length=255)),
                ('vpn', models.CharField(default='', max_length=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('chave', models.CharField(max_length=30)),
                ('ativa', models.BooleanField(default=True)),
                ('criptografia', models.CharField(choices=[('WPA', 'WPA'), ('WEP', 'WEP')])),
                ('ip_servidor', models.CharField(default='192.168.0.1', max_length=11)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('serial', models.CharField(blank=True, max_length=30)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresa')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.modelo_equipamento')),
                ('rede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.rede')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip', 'rede'), name='unique_ip_per_rede'), models.UniqueConstraint(fields=('nome', 'empresa'), name='unique_carro_per_empresa')],
            },
        ),
    ]
