# Generated by Django 5.1.2 on 2024-10-24 16:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloequipamentos',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('razao_social', models.CharField(max_length=255)),
                ('vpn', models.CharField(default='', max_length=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('ativa', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.modeloequipamentos')),
            ],
        ),
    ]
