# Generated by Django 5.1.2 on 2024-10-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='vpn_last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vpn_status',
            field=models.BooleanField(default=False),
        ),
    ]
