# Generated by Django 5.1.2 on 2024-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0002_alter_modeloequipamentos_modelo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede', models.CharField(max_length=20, unique=True)),
                ('chave', models.CharField(max_length=30)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa_id', models.IntegerField()),
                ('criptografia', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='modeloequipamentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
