# Generated by Django 5.1 on 2024-10-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0002_empresa_vpn_last_checked_empresa_vpn_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='vpn_last_checked',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='vpn_status',
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('vpn', models.CharField(default='', max_length=100)),
                ('ip_publico', models.CharField(default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('vpn_status', models.BooleanField(default=False)),
                ('vpn_last_checked', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresa')),
            ],
        ),
    ]
