# Generated by Django 5.1 on 2024-10-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0003_remove_empresa_vpn_last_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='vpn',
        ),
    ]
