# Generated by Django 5.1.2 on 2024-10-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0003_rede_alter_modeloequipamentos_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Empresas',
        ),
        migrations.RenameModel(
            old_name='ModeloEquipamentos',
            new_name='ModelosEquipamento',
        ),
        migrations.RenameModel(
            old_name='Rede',
            new_name='Redes',
        ),
    ]
