# Generated by Django 5.1 on 2024-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0004_remove_empresa_vpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='ip_publico',
            field=models.CharField(max_length=100),
        ),
    ]
