# Generated by Django 5.1.2 on 2024-10-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0004_rename_empresa_empresas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='redes',
            name='empresa_id',
        ),
        migrations.AddField(
            model_name='redes',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresas'),
        ),
    ]
