# Generated by Django 5.1.2 on 2024-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0005_remove_empresas_modelo_remove_redes_empresa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='criptografia',
            field=models.CharField(choices=[('WPA', 'WPA'), ('WEP', 'WEP')]),
        ),
    ]
