# Generated by Django 5.1.2 on 2024-10-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0006_alter_redes_criptografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresas')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.modelosequipamento')),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.redes')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip', 'rede'), name='unique_ip_per_rede')],
            },
        ),
    ]
