# Generated by Django 5.1 on 2024-10-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0006_alter_servidor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo_equipamento',
            options={'verbose_name': 'Modelo Equipamento', 'verbose_name_plural': 'Modelos Equipamento'},
        ),
        migrations.AlterField(
            model_name='servidor',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresa'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ip_publico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='vpn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
