# Generated by Django 5.1.2 on 2024-10-31 02:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0007_alter_modelo_equipamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_video', models.DateField()),
                ('hora_video', models.TimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('erased', models.BooleanField(default=False)),
                ('tamanho', models.IntegerField(blank=True, help_text='Tamanho do vídeo em MB', null=True)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('path_arquivo', models.CharField(blank=True, max_length=500, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectrans.carro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectrans.empresa')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.servidor')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
    ]
