# Generated by Django 5.1.2 on 2024-10-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
