# Generated by Django 5.1.2 on 2024-10-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0009_redes_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.empresas'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.modelosequipamento'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='rede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectrans.redes'),
        ),
        migrations.AddConstraint(
            model_name='carros',
            constraint=models.UniqueConstraint(fields=('carro', 'empresa'), name='unique_carro_per_empresa'),
        ),
    ]
