# Generated by Django 5.1.2 on 2024-11-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0009_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.IntegerField(null=True),
        ),
    ]
