# Generated by Django 5.1.2 on 2024-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0010_alter_carros_empresa_alter_carros_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
