# Generated by Django 5.1.2 on 2024-11-06 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0010_video_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='duracao',
            field=models.DurationField(blank=True, help_text='Duração do vídeo em segundos', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tamanho',
            field=models.IntegerField(blank=True, help_text='Tamanho do vídeo em KB', null=True),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('video_file', 'channel', 'carro', 'data_video'), name='unique_file_per_channel_in_car_at_date'),
        ),
    ]
