# Generated by Django 5.1.2 on 2024-11-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0011_alter_empresa_data_cadastro_alter_video_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tamanho',
            field=models.FloatField(blank=True, help_text='Tamanho do vídeo em KB', null=True),
        ),
    ]
