# Generated by Django 5.1.2 on 2024-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0012_alter_video_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede',
            name='ip_servidor',
            field=models.CharField(default='192.168.0.1', max_length=15),
        ),
    ]
