# Generated by Django 5.1.2 on 2024-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectrans', '0012_alter_carros_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redes',
            old_name='ip',
            new_name='ip_servidor',
        ),
        migrations.AlterField(
            model_name='carros',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
